CREATE DATABASE IF NOT EXISTS `Countries`;
USE `Countries`;

DROP TABLE IF EXISTS `Country`;
CREATE TABLE `Country`(
    idCountry INT NOT NULL auto_increment,
    name VARCHAR(50),
    iso VARCHAR(5),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(idCountry)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;